language: scala
scala:
  - 2.12.8
jdk: oraclejdk8

sudo: false

script:
  - sbt +test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_deploy:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/secring.gpg.enc -out local.secring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/pubring.gpg.enc -out local.pubring.gpg -d

deploy:
  - provider: script
    script: .travis/publish.sh
    skip_cleanup: true
    on:
      repo:HemaPartha/bootcamp-wk4
      branch: master
      jdk: oraclejdk8
      scala: 2.12.8


